// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDB4-XavAw6lFyAE9PFLshuE0LOmjdN_AM',
    appId: '1:538859494082:web:5785b9a50bd1a18556795b',
    messagingSenderId: '538859494082',
    projectId: 'room-reservation-d69c4',
    authDomain: 'room-reservation-d69c4.firebaseapp.com',
    databaseURL: 'https://room-reservation-d69c4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'room-reservation-d69c4.appspot.com',
    measurementId: 'G-GMFG0B09E1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsnyj3l-uKkXtxCZ1S0VLOXfpm4NYTez8',
    appId: '1:538859494082:android:79a6f0b76db971d156795b',
    messagingSenderId: '538859494082',
    projectId: 'room-reservation-d69c4',
    databaseURL: 'https://room-reservation-d69c4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'room-reservation-d69c4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJWjXhPsPSErJ0LnYJ3ozJXoQk5gVwvLU',
    appId: '1:538859494082:ios:759c9b816498257656795b',
    messagingSenderId: '538859494082',
    projectId: 'room-reservation-d69c4',
    databaseURL: 'https://room-reservation-d69c4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'room-reservation-d69c4.appspot.com',
    iosBundleId: 'com.example.zenithCoffeeShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJWjXhPsPSErJ0LnYJ3ozJXoQk5gVwvLU',
    appId: '1:538859494082:ios:759c9b816498257656795b',
    messagingSenderId: '538859494082',
    projectId: 'room-reservation-d69c4',
    databaseURL: 'https://room-reservation-d69c4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'room-reservation-d69c4.appspot.com',
    iosBundleId: 'com.example.zenithCoffeeShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDB4-XavAw6lFyAE9PFLshuE0LOmjdN_AM',
    appId: '1:538859494082:web:f06db4778ee9469e56795b',
    messagingSenderId: '538859494082',
    projectId: 'room-reservation-d69c4',
    authDomain: 'room-reservation-d69c4.firebaseapp.com',
    databaseURL: 'https://room-reservation-d69c4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'room-reservation-d69c4.appspot.com',
    measurementId: 'G-H011WEG6Y3',
  );

}